collections:
  landingpage:
    output: false
  promo:
    output: false
defaults:
  - scope:
      path: ""
      type: landingpage
    values:
      lang: en
  - scope:
      path: ""
      type: promo
    values:
      lang: en
title: codeworx.at
include: [vendor]
vendor:
   _internal: Template
excerpt_separator: <!-- more -->
lang: de
description: codeworxs description
url: https://www.codeworx.at
languages: [de,en]
langlink:
  de: /
  en: /en
