plugins: 
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
pagination:
  enabled: true
  debug: false
  per_page: 9
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
collections:
  landingpage_de:
    output: false
  landingpage_en:
    output: false
  promo_de:
    output: false
  promo_en:
    output: false
  jobs_de:
    permalink: /karriere/:path
    order:
      - junior.md
      - senior.md
      - architekt.md
    output: true
  jobs_en:
    permalink: /jobs/:path
    output: true
  projects:
    output: true
    sort_by: date
  projekte:
    output: true
    sort_by: date
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      category: dev
      lang: en
  - scope:
      path: ""
      type: projekte
    values:
      layout: project
      category: dev
      lang: de
  - scope:
      path: ""
      type: landingpage_en
    values:
      lang: en
  - scope:
      path: ""
      type: landingpage_de
    values:
      lang: de
  - scope:
      path: ""
      type: promo_en
    values:
      lang: en
  - scope:
      path: ""
      type: promo_de
    values:
      lang: de
  - scope:
      path: ""
      type: jobs_de
    values:
      layout: job
      lang: de
  - scope:
      path: ""
      type: jobs_en
    values:
      layout: job
      lang: en
title: codeworx.at
permalink: pretty
markdown: kramdown
include: [vendor]
vendor:
   _internal: Template
excerpt_separator: <!-- more -->
lang: de
description: codeworxs description
url: https://www.codeworx.at