collections:
  landingpage:
    output: false
  promo:
    output: false
  projects:
    output: true
    sort_by: date
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      lang: en
  -
    scope:
      path: ""
      type: landingpage
    values:
      lang: en
  -
    scope:
      path: ""
      type: promo
    values:
      lang: en
title: codeworx.at
include: [vendor]
vendor:
   _internal: Template
excerpt_separator: <!-- more -->
lang: de
description: codeworxs description
url: https://www.codeworx.at
languages: [de,en]
langlink:
  de: /
  en: /en
clients:
  orf: Österreichischer Rundfunk
  insite: InsiteIT
employees:
  rasc: Raphael Schwarz